### ISSUE TITLE
Installation issue?

### ISSUE THREAD

**Issue by rubyFeedback** [Skitia/SkitiaNPCs#3]
I have had an installation issue, perhaps related to another mod. I can get the error message from my windows machine (I normally use linux; right now I am typing this from my linux machine, so I can not copy/paste the error as-is).

I think I installed a few mods, then tried skitia via weidu but it told me some parsing error in a file so it has to be rolled back or
something. Most other mods I installed work fine though, so I am unsure about the error.

**Comment by Skitia** [comment]
I'll need the weidu log, or a screen of the parsing (If it happened again) to fix it.

**Comment by Skitia** [comment]
I'll need to see the error message you got, then I can either fix you or
tell you if another mod is causing the problem.

Whenever you get a chance, definitely show me what the error was so we can
get this troubleshooted for you.
