### ISSUE TITLE
Duplicate files due to casesentiveness.

### ISSUE THREAD

**Issue by Frenzgyn** [Skitia/SkitiaNPCs#4]
Hello there! Really minor bug in the gamefiles due to casesensitiveness: 

X3EDay.ogg and X3Eday.ogg conflict on unzipping in windows environment, X3EDay (capital "D") is the old one. 

Thanks for the mods and the furious pace of updates and bugfixes!

**Comment by Skitia** [comment]
Thank you for reporting this, it should be fixed.
